### ISSUE TITLE
undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by TenTen-Teng** [bgshih/seglink#14]
When I run "./manage.py train exp/sgd pretrain", the error shows:
Traceback (most recent call last):
  File "solver.py", line 12, in <module>
    import model
  File "/home/tengli1107/seglink/seglink/model.py", line 6, in <module>
    import ops
  File "/home/tengli1107/seglink/seglink/ops.py", line 188, in <module>
    oplib = load_oplib(LIB_NAME)
  File "/home/tengli1107/seglink/seglink/ops.py", line 22, in load_oplib
    oplib = tf.load_op_library(lib_copy_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/lib956d0286_seglink.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

How can I solve this problem? I'm using ubuntu16.04, tensorflow 1.8, gcc 5.4.
I also tried on ubuntu 14.04, still got the same problem. 

Thank you

**Comment by MatiasKopp** [comment]
Hi, I ran into the same problem yesterday. I solved it by uninstalling tensorflow and reinstalling it at version 1.3 with:
`pip install tensorflow==1.3`

**Comment by TenTen-Teng** [comment]
@MatiasKopp Thank you so much. Your solution works on me. However, after reinstalling tensorflow, there's another error comes up: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKNS_6StatusE 
Do you know how to solve this?

**Comment by FakerYFX** [comment]
I meet the same problem: tensorflow.python.framework.errors_impl.NotFoundError: /data/20180809/tmp/libca051180_seglink.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
@bgshih @TenTen-Teng @MatiasKopp

**Comment by Bachelorwangwei** [comment]
@MatiasKopp when i reinstall the tensorflow==1.3.0， i meet the same error as @TenTen-Teng 。
Did you meet this situation and how to solve this problem？

**Comment by Shualite** [comment]
https://github.com/yulequan/PU-Net/issues/5    maybe we should recompile the .so file or re-install tensorflow <1.4

**Comment by TangLinJie** [comment]
I meet the same error as @TenTen-Teng, I solve this question by using [tensorflow-gpu==1.0.0](https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0-cp36-cp36m-linux_x86_64.whl) with python3.5 cudnn5.1 cuda8.0.

**Comment by Donaghys** [comment]
请问不更换版本的前提下这个问题如何解决？
